### ISSUE TITLE
Невозможно заставить простую демонстрацию работать

### ISSUE THREAD

**Issue by sk-t3ch** [TheLongRunSmoke/bird-haar#1]
Здравствуйте, я не могу заставить это работать. Пожалуйста, не могли бы вы помочь?
(Hello, I am unable to get this to work. Please can you help?)

```
import cv2 as cv

cascade = cv.CascadeClassifier('./bird-haar/cascade_226.xml')
# cascade = cv.CascadeClassifier('./bird-haar/cascade_114.xml')

def detectAndDisplay(frame):
    frame_gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    # frame_gray = cv.equalizeHist(frame_gray)
    detections = cascade.detectMultiScale(frame_gray,  1.05, 3)
    for (x,y,w,h) in detections:
        center = (x + w//2, y + h//2)
        frame = cv.ellipse(frame, center, (w//2, h//2), 0, 0, 360, (255, 0, 255), 4)
    cv.imshow('Capture - Detection', frame)

cap = cv.VideoCapture(0)
cap.set(cv.CAP_PROP_FRAME_WIDTH, 640)
cap.set(cv.CAP_PROP_FRAME_HEIGHT, 480)

while True:
    ret, frame = cap.read()
    if frame is None:
        break
    detectAndDisplay(frame)
    if cv.waitKey(10) == 27:
        break


```

 
<img width="640" alt="Screenshot 2021-04-29 at 13 59 36 1" src="https://user-images.githubusercontent.com/25009814/116554654-5c0ff100-a8f3-11eb-8a5c-12a494cb498e.png">

Благодарность
(Thanks!)

---
Я не говорю по-русски, весь текст переведен.
(I cannot speak Russian, all text has been translated.)

**Comment by TheLongRunSmoke** [comment]
Hi. You can check this code as an example https://github.com/TheLongRunSmoke/birdfeeder/blob/master/cv-api/app/detector.py 
However, this cascade made for detection birds that fill significant part of a frame.

**Comment by sk-t3ch** [comment]
Thank you!
I have tried again and managed to detect a chicken :)
<img width="1280" alt="Screenshot 2021-04-29 at 15 16 41" src="https://user-images.githubusercontent.com/25009814/116565746-0d1b8900-a8fe-11eb-9804-6a20ae26f701.png">

I think I will move onto transfer learning a mobilenet model.
